config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  get 'tops/index'

  # get 'sessions/new'

##  heroku 登録用に追記
##  root 'tops#blogs' これじゃダメだった。なんで？↓エラーでルーティングが出てて何となく表示させたいパスにしたら通った！
  # root 'blogs#index'

##  get '/contacts', to: 'contacts#index'#課題１問い合わせ画面作成
  resources :contacts

  get '/stocks', to: 'stocks#index'#小課題rails入門４

##  get '/blogs', to: 'blogs#index' #追記する
  resources :blogs

##  ログインシステムのルーティング設定
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
##  ログインシステム：起動時にログイン画面が表示されるようにする
  # root 'sessions#new'

  ##  叩いたのお気に入り機能で追記
  resources :favorites, only: [:create, :destroy]

  ##  ログインシステム：最初にトップ画面に飛ぶように設定
  resources :tops

  ##  ログインシステム：起動時にログイン画面が表示されるようにする
  root 'tops#index'

  ##  ActionMailer の設定にて追記
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  ##  画像アップローダー の設定にて追記
  resources :feeds
  
end

app/models/blog.rb
class Blog < ApplicationRecord
	validates :content,presence: true
# 「1文字以上」
	validates :content,    length: { minimum: 1 }
# 「140文字以下」
  validates :content,    length: { maximum: 140 }

# アソシエーション設定一対多の多側
  belongs_to :user
# アソシエーション設定多対多の多側
	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user

# 画像アップロードの設定
	mount_uploader :image, ImageUploader

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy] # DRYにてアクションの前に設置
  before_action :set_login, only: [:new, :edit, :show] # ログインしていないとトップに戻す

  def index
    @blogs = Blog.all #
  end

  def new
    @blog = Blog.new
#    binding.pry
  end

  def create
#    Blog.create(blog_params) # ストロングパラメーターのメソッドを定義したので使用した
#    Blog.create(params[:blog]) #インスタンス関数を使って全ての情報を取得している、但しセキュリティに難あり。
#    Blog.create(title: params[:blog][:title], content: params[:blog][:content]) #ハッシュを使わないでカラムを一つずつ取得している
#    redirect_to new_blog_path
    @blog = Blog.new(blog_params) #バリデーションの機能追加
    @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'ブログを登録しました！' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  #   if @blog.save
  #     # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
  #     redirect_to blogs_path, notice: "つぶやきました！"
  #   else
  #     # 入力フォームを再描画します。
  #     render 'new'
  #   end
  # end

  # アソシエーションの叩いたで設定し直した

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end
  # 定義する 一覧表示の詳細リンクを作成した際に作成した
  # def show
  #   @blog = Blog.find(params[:id])
  # end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update #アップデート対象となるidをfindで取得し、その後createと同様にupdate出来たらの分岐を作成
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "つぶやきを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"つぶやきを削除しました！"
  end

    private #噂のストロングパラメーター。設定しないと無関係のカラムを編集出来るので設定する。

  def blog_params
    params.require(:blog).permit(:title, :content, :image)
  end

  # idをキーとして値を取得するメソッド(DRY（Don’t Repeat Yourself）)shou edit update　で
  # @blog = Blog.find(params[:id]) をメソッド定義しているメソッド。
  # また、ルーティングで呼ばれる訳ではないので、ストロングパラメータに設置
  def set_blog
      @blog = Blog.find(params[:id])
  end

  # ログインしないと投稿、編集、詳細が開けないようにする
  def set_login
    # binding.pry
    unless !current_user.nil?
      redirect_to tops_path, notice:"まずはログインしたまえ！"
    end
  end


end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_footer.html.erb
    <footer class="footer">
      <p>Copyright © 2016 DIVE INC All RIGHTS RESERVED.</p>
    </footer>

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,data: { confirm: '本当につぶやきますか？' } ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p><%= notice %></p>

  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %><br>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :user_image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <%= form.submit class: "btn_index" %>

<% end %>

app/views/blogs/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Bootstrap</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bootstrap</a>
    </div>

    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "Profile", user_path(current_user.id) %></li>
          <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
          <!-- 171212 ログインした後にプロフィール画面からブログに戻れないから追記！！-->
          <li><%= link_to "blogs", blogs_path(current_user.id) %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Login", new_session_path %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

<header class="header clearfix">
  <a><%= link_to 'ホーム', blogs_path , class: "btn btn-warning" %></a>
  <a><%= link_to 'つぶやき', new_blog_path ,  class: "btn btn-warning" %></a>
</header>

<div class="div_header">
  <a>生きてればいい事あるさ〜。</a>
  <!-- <a href=""><img src="assets/bootstrap01.jpeg" class="area_logo img-responsive"></a> -->
  <a href=""><img src="assets/bootstrap01.jpeg" class="area_logo img-responsive"></a>
</div>

app/views/blogs/edit.html.erb
<!--<%= form_with(model: @blog, local: true) do |form| %>-->
<!--  <% if @blog.errors.any? %>-->
<!--    <div id="error_explanation">-->
<!--      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>-->
<!--      <ul>-->

<!--      <% @blog.errors.full_messages.each do |msg| %>-->
<!--        <li><%= msg %></li>-->
<!--      <% end %>-->
<!--      </ul>-->
<!--    </div>-->
<!--  <% end %>-->

<!--<h1>ブログ編集画面</h1>-->
<!--  <div class="blog_title">-->
<!--    <%= form.label :title %>-->
<!--    <%= form.text_field :title %>-->
<!--  </div>-->
<!--  <div class="blog_title">-->
<!--    <%= form.label :content %>-->
<!--    <%= form.text_field :content %>-->
<!--  </div>-->
<!--  <%= form.submit %>-->
<!--<% end %>-->
<!--<%= link_to 'ブログ一覧画面にもどる', blogs_path %><br>-->

<h1>つぶやき編集画面</h1>

  <%= render 'form' %>

app/views/blogs/index.html.erb
<div class="container">
  <h1>つぶやき一覧</h1>
  <p><%= notice %></p>

  <div class="wrapper clearfix row">
    <table class="tbl">

      <tr>
        <th>内容</th>
      </tr>

      <% @blogs.each do |blog| %>
      <tr class="btn-group" role="group" aria-label="...">
        <th><%= blog.content %></th>
        <td button type="button" class="col-xs-12 col-sm-4 col-md-2 btn btn-info btn-sm">
          <%= link_to '詳細', blog_path(blog.id) %></td>

        <!--171214ブログモデルに存在するユーザーID とカレントユーザーが同じなら編集と削除ができるようにしたい-->
        <% if blog.user_id == current_user.id %>
          <td button type="button" class="col-xs-12 col-sm-4 col-md-2 btn btn-warning btn-sm">
            <%= link_to '編集', edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' } %></td>
          <td button type="button" class="col-xs-12 col-sm-4 col-md-2 btn btn-danger btn-sm">
            <%= link_to '削除', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
        <%end%>

        <!--180201 画像の挿入 -->
        <td>
          <strong>Image:</strong>
          <%= image_tag blog.image %>
        </td>

      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/blogs/new.html.erb
<!--　DRYでView も共通化出来る、パーシャルを作成し、そこにView内容を書き込にnewの実態は２行で済む-->
<!--<%= form_with(model: @blog, local: true) do |form| %>-->
<!--  <% if @blog.errors.any? %>-->
<!--    <div id="error_explanation">-->
<!--      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>-->
<!--      <ul>-->

<!--      <% @blog.errors.full_messages.each do |msg| %>-->
<!--        <li><%= msg %></li>-->
<!--      <% end %>-->
<!--      </ul>-->
<!--    </div>-->
<!--  <% end %>-->

<!--  <div class="blog_title">-->
<!--    <%= form.label :title %>-->
<!--    <%= form.text_field :title %>-->
<!--  </div>-->
<!--  <div class="blog_title">-->
<!--    <%= form.label :content %>-->
<!--    <%= form.text_field :content %>-->
<!--  </div>-->
<!--  <%= form.submit %>-->
<!--<% end %>-->

 <h2>つぶやく</h2>

  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>つぶやき詳細画面</h1>
<p>内容: <%= @blog.content %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image %>
</p>

<% unless @blog.user == current_user %>
  <% if @favorite.present? %>
    <button type="button" class="btn btn-danger">
      <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete %>
    </button>
  <% else %>
    <button type="button" class="btn btn-prymary">
      <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post %>
    </button>
  <% end %>
<% end %>