config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  get 'tops/index'

  # get 'sessions/new'

##  heroku 登録用に追記
##  root 'tops#blogs' これじゃダメだった。なんで？↓エラーでルーティングが出てて何となく表示させたいパスにしたら通った！
  # root 'blogs#index'

##  get '/contacts', to: 'contacts#index'#課題１問い合わせ画面作成
  resources :contacts

  get '/stocks', to: 'stocks#index'#小課題rails入門４

##  get '/blogs', to: 'blogs#index' #追記する
  resources :blogs

##  ログインシステムのルーティング設定
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
##  ログインシステム：起動時にログイン画面が表示されるようにする
  # root 'sessions#new'

  ##  叩いたのお気に入り機能で追記
  resources :favorites, only: [:create, :destroy]

  ##  ログインシステム：最初にトップ画面に飛ぶように設定
  resources :tops

  ##  ログインシステム：起動時にログイン画面が表示されるようにする
  root 'tops#index'

  ##  ActionMailer の設定にて追記
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  ##  画像アップローダー の設定にて追記
  resources :feeds
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twc</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- 18018 ナブバーの情報を記述（ハンバーガーメニューね）-->
    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Bootstrap</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Bootstrap</a>
        </div>

        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <!-- 18018 ログイン状態に関係なく表示-->
            <button type="button" class="btn btn-info">
              <li><%= link_to 'home', tops_path %></li>
            </button>
            <button type="button" class="btn btn-info">
              <li><%= link_to 'つぶやき', new_blog_path %></li>
            </button>

            <!-- 18018 ログイン状態によって表示内容を変更-->
            <% if logged_in? %>
              <button type="button" class="btn btn-info">
                  <li><%= link_to "Profile", user_path(current_user.id) %></li>
              </button>
              <button type="button" class="btn btn-success">
                  <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
              </button>
              <!-- 171212 ログインした後にプロフィール画面からブログに戻れないから追記！！-->
              <button type="button" class="btn btn-warning">
                  <li><%= link_to "blogs", blogs_path(current_user.id) %></li>
              </button>
            <% else %>
              <button type="button" class="btn btn-warning">
                <%= link_to "Sign up", new_user_path %>
              </button>
              <button type="button" class="btn btn-warning">
                <%= link_to "Login", new_session_path %>
              </button>
            <% end %>
          </ul>
        </div>

      </div>
    </nav>

  </head>

  <body>
    <!-- 180118 全ての画面の背景に同じ画像を持ってこようとするとアプリケーション-->
    <div class="jumbotron">
      <!-- 180118 これは何？？-->
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <!-- 180118 イールドには .erb の内容が入ってくる-->
      <%= yield %>

      <!-- 180118 フッターは共通部分なのでここに定義した-->
      <footer class="footer">
        <p>Copyright © 2016 DIVE INC All RIGHTS RESERVED.</p>
      </footer>
    </div>

  </body>
</html>